version: '2'
services:
  mysql:
    hostname: mysql
    image: mysql:5.7.17
    # network_mode: "host" # 如果需要容器使用宿主机IP(内网IP)，则可以配置此项
    container_name: mysql # 指定容器名称，如果不设置此参数，则由系统自动生成
    restart: unless-stopped # 设置容器自启模式
    privileged: true
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci # 设置utf8字符集
    environment:
      - TZ=Asia/Shanghai # 设置容器时区与宿主机保持一致
      - MYSQL_ROOT_PASSWORD=root # 设置root密码
    volumes:
       - ./volume/data:/var/lib/mysql # 映射数据库保存目录到宿主机，防止数据丢失
       - ./conf:/etc/mysql/conf.d # 映射数据库配置文件
    ports:
        - "3306:3306"